---
subscriptions:
  crunchyData:
    enabled: false
    description: Crunchy-Data PostgreSQL Operator
    apiResource: postgresclusters.postgres-operator.crunchydata.com
    namespace: openshift-operators
    name: crunchy-postgres-operator-rhmp
    channel: v5
    source: redhat-marketplace
    sourceNamespace: openshift-marketplace
  openshiftGitOps:
    enabled: false
    description: OpenShift GitOps Operator
    apiResource: gitopsservices.pipelines.openshift.io
    namespace: openshift-operators
    name: openshift-gitops-operator
    channel: gitops-1.16
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    config:
      argoCDClusterNamespace: __OVERWRITE_ME__
  openshiftKeycloak:
    enabled: false
    description: Red Hat Keycloak Operator
    apiResource: keycloaks.k8s.keycloak.org
    namespace: rhbk-operator
    name: rhbk-operator
    channel: stable-v24
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces: []
  openshiftPipelines:
    enabled: false
    description: OpenShift Pipelines Operator
    namespace: openshift-operators
    name: openshift-pipelines-operator-rh
    channel: pipelines-1.19
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  openshiftTrustedArtifactSigner:
    enabled: false
    description: Red Hat Trusted Artifact Signer Operator
    apiResource: securesigns.rhtas.redhat.com
    namespace: openshift-operators
    name: rhtas-operator
    channel: stable-v1.2
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  openshiftTrustedProfileAnalyzer:
    enabled: false
    description: Red Hat Trusted Profile Analyzer
    apiResource: trustedprofileanalyzers.rhtpa.io
    namespace: tssc-tpa
    name: rhtpa-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces:
        - tssc-tpa
  advancedClusterSecurity:
    enabled: false
    description: Red Hat Advanced Cluster Security Operator
    apiResource: centrals.platform.stackrox.io
    channel: rhacs-4.8
    namespace: rhacs-operator
    name: rhacs-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
  developerHub:
    enabled: false
    description: Red Hat Developer Hub Operator
    apiResource: backstages.rhdh.redhat.com
    namespace: openshift-operators
    name: rhdh
    channel: fast-1.6
    source: redhat-operators
    sourceNamespace: openshift-marketplace
